### ISSUE TITLE
Tabs vs. Spaces: EditorConfig settings and Eclipse formatter settings are inconsistent

### ISSUE THREAD

**Issue by UrsMetz** [ocelot-wars/ocelot-wars#16]
I think our code style settings in the exported Eclipse settings and our `.editorconfig` file are contradictory: If I'm not mistaken the exported Eclipse settings say that we use tabs for indentation (https://github.com/ocelot-wars/ocelot-wars/blob/b3937e02ad02af298485f06895f8bdbcfbce408b/ocelot-wars-code-conventions.xml#L306).
The EditorConfig states `Spaces` as our indentation character.

I'm leaning towards spaces but am also fine with tabs but we should find a consistent setting.

**Comment by almondtools** [comment]
Spaces ok for me.

**Comment by UrsMetz** [comment]
@almondtools so would you change the Eclipse settings as we have discussed some time ago?
Maybe we should also consider something like [Spotless](https://github.com/diffplug/spotless)?
I might find the time so have a look at Spotless and create a pull request for introducing it.

**Comment by UrsMetz** [comment]
@almondtools cool, thanks :-)
