### ISSUE TITLE
Build file string style and version management

### ISSUE THREAD

**Issue by UrsMetz** [ocelot-wars/ocelot-wars#19]
In the pull request #15 we started a discussion whether we want to use centralized version strings or not. So do we want to use
```
ext.junit5Version = '5.1.0-M1'
...
dependencies {
    testImplementation "org.junit.jupiter:junit-jupiter-api:${junit5Version}"
    ...
}
```
or
```
dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.1.0-M1'
    ...
}
```

A related question whether we want to use single or double quotes for strings in the Gradle build files. As pointed out by @BlueIce the [Groovy language style](http://groovy-lang.org/style-guide.html) suggest to use single quotes for "plain" strings and double quotes for strings with interpolation

**Comment by UrsMetz** [comment]
I'm in favor of centralized version strings and following the Gradle language style guide for the use of single and double quotes.

**Comment by BlueIce** [comment]
> I'm in favor of centralized version strings and following the Gradle language style guide for the use of single and double quotes.

That's fine with me.

**Comment by UrsMetz** [comment]
After discussing this with @almondtools and @BlueIce we settled on not extracting the version numbers. This also means we don't have to decide on single versus double quotes.
